[ip]
name = "adder"
description = "A basic adder"
version = "0.1.0"

# See more keys and their definitions at https://cdotrus.github.io/orbit/reference/manifest.html

[dependencies]
amp = "1.0.0"

[dev-dependencies]
veriti = "0.1.0"