[ip]
name = "summit"
description = "A collection of simple hardware units"
version = "0.1.0"
source = "https://github.com/hyperspace-labs/summit/archive/{{orbit.ip.version}}.zip"
public = ["/rtl", "!/rtl/top.v"]

# See more keys and their definitions at https://cdotrus.github.io/orbit/reference/manifest.html

[dependencies]
gates = "1.0.1"