name: test
on:
  push:

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
        image: cdotrus/groovy-guitar
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Log all tool versions
        run: |
          orbit --version  
          python --version
          ghdl --version
        
      - name: Configure orbit profile
        run: |
          git clone https://github.com/cdotrus/orbit-profile.git "$(orbit env ORBIT_HOME)/profiles/cdotrus"
          pip install -r "$(orbit env ORBIT_HOME)/profiles/cdotrus/requirements.txt"
          orbit config --append include="profiles/cdotrus/config.toml"

      - name: Install missing Python packages
        run: |
          pip install -r mdl/requirements.txt

      - name: Verify adder (8 bits)
        run: |
          orbit plan --clean --plugin gsim --top adder
          orbit b -- --lib veriti -g WORD_SIZE=8
          veriti check --log ./build/gsim/events.log

      - name: Verify adder (20 bits)
        run: |
          orbit plan --clean --plugin gsim --top adder
          orbit b -- --lib veriti -g WORD_SIZE=20
          veriti check --log ./build/gsim/events.log